# netlify.toml
[[redirects]]
  from = "/api/*"
  to   = "https://nae.grup.com.ng/:splat"
  status = 200
  force  = true

# Single Page App fallback (important for React Router)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
